export const ActionTypes = {
  GET_LINE_CHART_DATA: 'GET_LINE_CHART_DATA',
  GET_PIE_CHART_DATA: 'GET_PIE_CHART_DATA',
  GET_TABLE_DATA: 'GET_TABLE_DATA',
  GET_NUMBER_CARD_DATA: 'GET_NUMBER_CARD_DATA',
  GET_CHARACTER_DATA: 'GET_CHARACTER_DATA'
};

export default ActionTypes;
